### ISSUE TITLE
Erreur d'Installation

### ISSUE THREAD

**Issue by Dreamer68** [GladysProject/gladys-mqtt#1]
Bonjour,
j’ai essayé d’installer le module gladys-mqtt et j’ai eu une erreur d’installation qui s’est affiché en haut à droite ([https://www.dropbox.com/s/ghfa6cj6syviajz/bug.JPG?dl=0]) et je n’arrive pas a l’installer pouvez-vous m’aidez ?

Merci d’avance

**Comment by Pierre-Gilles** [comment]
My bad, j'ai trouvé l'erreur, c'est tout bête. Dans l'image Raspbien Jessie Lite que j'ai utilisée, git n'est pas inclus. Or l'installation est basée sur git.

Un : 

```
sudo apt-get install git
```

Sur le Raspberry Pi corrige le problème :) 

Merci encore pour l'issue, je corrige ça sur l'image !

**Comment by Dreamer68** [comment]
Merci beaucoup !
